version: '3'
services:
    db:
        image: mariadb:10.3.35
        volumes:
          - ./db_data:/var/lib/mysql
        ports:
            - "13306:3306"
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: rootpasswd
volumes:
    db_data:
